% checking integrality gap of SDP

DEBUG = true;

sigma = 0;
s = 4;
V = 2*randint(s, 9)-ones(s,9)
Y = [V(:,1) V(:,2) V(:,3); ...
     V(:,2) V(:,1) V(:,3); ...
     V(:,6) V(:,4) V(:,5); ...
     V(:,6) V(:,5) V(:,4); ...
     V(:,8) V(:,9) V(:,7); ...
     V(:,7) V(:,9) V(:,8)]

SDPugJustPhase_pos(Y, sigma, DEBUG)